tarea/proyecto/tarea/Dashboard/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Dashboard.views import DashboardClass

app_name = 'Dashboard'

urlpatterns = [
    path('Dashboard', DashboardClass.as_view(), name='Dashboard')
]

tarea/proyecto/tarea/Landing/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Landing.views import LandingClass

app_name = 'Landing'

urlpatterns = [
    path('', LandingClass.as_view(), name='Landing')
]

tarea/proyecto/tarea/Login/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Login.views import LoginClass

app_name = 'Login'

urlpatterns = [
    path('', LoginClass.as_view(), name='Login')
]

tarea/proyecto/tarea/Registro/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Registro.views import RegistrateView

app_name = 'Registro'

urlpatterns = [
    path('', RegistrateView.as_view(), name='Registro'),
]

tarea/proyecto/tarea/tarea/urls.py
from django.contrib import admin
from django.urls import include, path, re_path 
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('Landing.urls')),
    path('Login/', include ('Login.urls')),
    path('logout/', logout_then_login, name= 'logout'),
    path('Dashboard/', include ('Dashboard.urls')),
    path('registrate/', include ('Registro.urls')),
]

tarea/proyecto/tarea/Dashboard/models.py
from django.db import models

# Create your models here.

tarea/proyecto/tarea/Landing/models.py
from django.db import models

# Create your models here.

tarea/proyecto/tarea/Login/models.py
from django.db import models

# Create your models here.
class Login (models.Model):
    nombre = models.CharField(max_length = 254,null=False)
    ap_pat = models.CharField(max_length = 254,null=False)
    ap_mat = models.CharField(max_length = 254,null=False)
    edad = models.IntegerField(null=False)

tarea/proyecto/tarea/Registro/models.py
from django.db import models

# Create your models here.

# class ModelRegistro(models.Model):
#     nombre = models.CharField(max_length = 254,null = False)
#     edad = models.IntegerField(null=False)
#     direccion = models.CharField(max_length = 254,null = False)
#     genero = models.CharField(max_length = 254,null = False)
#     pais = models.CharField(max_length = 254,null = False)
#     estado = models.CharField(max_length = 254,null = False)

tarea/proyecto/tarea/Registro/forms.py
from django.contrib.auth.models import User
from django import forms

ERROR_MESSAGE_USER = {'unique' : 'El Username ya se encuentra registrado', 'invalid' : 'usuario o contraseña incorrecto'}
ERROR_MESSAGE_PASSWORD = {'required' : 'El password es requerido'}
ERROR_MESSAGE_EMAIL = {'invalid' : 'Ingrese un correo valido'}
ERROR_MESSAGE_PHONE = {'invalid' : 'Formato numero incorrecto'}

class RegisterBusinessForm(forms.ModelForm):
    first_name = forms.CharField(label='', required=True)
    last_name = forms.CharField(label='', required=True)
    password = forms.CharField(max_length = 20,required=True, widget = forms.PasswordInput(), error_messages = ERROR_MESSAGE_PASSWORD )
    email = forms.CharField( required = True, error_messages = ERROR_MESSAGE_EMAIL)

    def __init__(self, *args, **kwargs):
        super(RegisterBusinessForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update( {'id': 'username_create', 'class': 'form-control', 'placeholder': 'usuario'} ) # Esto es un input en HTML <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name = "password" required>
        self.fields['first_name'].widget.attrs.update( {'id': 'first_name_create', 'class': 'form-control', 'placeholder': 'Nombre'} )
        self.fields['last_name'].widget.attrs.update( {'id': 'last_name_create', 'class': 'form-control', 'placeholder': 'Apellidos'} )
        self.fields['password'].widget.attrs.update( {'id': 'password_create', 'class': 'form-control', 'placeholder': 'Contraseña'} )
        self.fields['email'].widget.attrs.update( {'id': 'email_create', 'class': 'form-control', 'placeholder': 'Correo Electrónico'} )

    class Meta:
        model = User    
        fields = ['username', 'email', 'first_name', 'last_name', 'password']

tarea/proyecto/tarea/Dashboard/views.py
from django.shortcuts import render, redirect
from django.views.generic import View

class DashboardClass(View):
    templates_oke = 'Dashboard/dashboard.html'
    def get(self, request, *args, **kwargs):
        print("GET")
        return render(request, self.templates_oke,{})

tarea/proyecto/tarea/Landing/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.views.generic import View
from django import template

# Importar metodo de auntenticacion
from django.contrib.auth import authenticate

class LandingClass(View):
    templates_ok = 'Landing/landing.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.templates_ok,{})

tarea/proyecto/tarea/Login/views.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import redirect
from django.contrib.auth import authenticate
from django import template

from django.contrib.auth import login as login_django

class LoginClass(View):
    templates = 'Login/index.html'
    templates_ok = 'Landing/landing.html'
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('Dashboard:Dashboard')
        return render(request, self.templates,{})

    def post(self, request, *args, **kwargs):
        user_post = request.POST['user']
        password_post = request.POST['password']

        user_session = authenticate(username = user_post, password=password_post)

        if user_session is not None:
            login_django(
                request, user_session
            )
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('Dashboard:Dashboard')
        else: 
            self.message = 'Usuario o contraseña incorrecto'
        
        return render(request, self.templates, self.get_context())

    def get_context(self):
        return{
            'error':self.message,
        }

tarea/proyecto/tarea/Registro/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from Registro.forms import RegisterBusinessForm
from django.shortcuts import redirect
# Create your views here.

class RegistrateView(FormView):
    template_name = 'Login/registro-usuarios.html'
    # GET
    def get(self, request, *args, **kwargs):
        form = RegisterBusinessForm(request.GET or None)
        context = {
            'form_get' : form
        }
        return render(request, self.template_name, context)

    # POST
    def post(self, request, *args, **kwargs):
        form = RegisterBusinessForm(request.POST or None)

        if form.is_valid():
            self.object = form.save(commit = False)
            self.object.set_password(self.object.password)
            self.object.save()
        return redirect('Login:Login')

tarea/proyecto/tarea/templates/Dashboard/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %}
</head>
<body background="https://img.myloview.es/cuadros/patron-web-textura-para-fondo-de-pantalla-rellenos-fondo-de-la-pagina-web-400-119131393.jpg">
    <div style="text-align: center;">
        <br>
        <br>
        <br>
        <br><br>
        <h3>Informacion del usuario</h3>
        <br><br>
        <h4 style="color:red">Nombre de Usuario: {{request.user.username}}</h4>
        <h4 style="color:red">Nombre de la persona{{request.user.first_name}}</h4>
        <h4 style="color:red">Apellido de la persona {{request.user.last_name}}</h4>
        <h4 style="color:red">Email {{request.user.email}}</h4>
        <br>
<a href="{% url 'logout' %}">Cerrar sesion</a>
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

tarea/proyecto/tarea/templates/Landing/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing</title>
    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %}
</head>
<body background="https://img.myloview.es/cuadros/patron-web-textura-para-fondo-de-pantalla-rellenos-fondo-de-la-pagina-web-400-119131393.jpg">
    <br>
    <div class="mx-auto" style="width: 200px;">
        <br>
        <div style="text-align: center;">
            <img src="https://cdn.computerhoy.com/sites/navi.axelspringer.es/public/media/image/2018/08/fondos-pantalla-full-hd-animales_4.jpg?fit=1000%2C530&amp;ssl=1" alt="..." class="rounded-circle" style="width: 100px;">
        </div>
        <br>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100" src="https://i.pinimg.com/originals/9a/35/37/9a3537acdb986a3798211346f59e5546.jpg" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="https://i.pinimg.com/originals/10/24/bd/1024bda12ba9fe9a4eb34e600fbeef8f.jpg" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="https://i.pinimg.com/236x/6e/da/81/6eda81a0995bdbeef5875db6418d1a80.jpg" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <br>
          <div style="text-align: center;">
            <a href="{% url 'Login:Login'%}">Ir a Login</a>
          </div>
          
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

tarea/proyecto/tarea/templates/Login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Como integrar Django y Bootstrap 4 </title>

    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %}
</head>
<body background="https://img.myloview.es/cuadros/patron-web-textura-para-fondo-de-pantalla-rellenos-fondo-de-la-pagina-web-400-119131393.jpg">
    <br>
    <div class="mx-auto" style="width: 200px;">
        <div class="container">
            <form action="" method="POST">
                <!-- init cifrado -->
                    {% csrf_token%}
                <!-- end cifrado -->
            <!-- init image -->
            <div class="form-group" style="text-align: center;"> 
                <br>
                <div style="text-align: center;">
                <img src="https://joesknowsfood.com/wp-content/uploads/2018/01/instagram-logo-vector-download-200x200.jpg" alt="..." class="rounded-circle" style="width: 100px;">
            </div>
            <!-- end image -->
                <br>
                <div class="form-group">
                    <input type="text" class="form-control border border-danger" placeholder="Email" name="user" required>
                </div>
                <div class="form-group">
                   <input type="password" class="form-control border border-danger" placeholder="Password" name="password" required> 
                </div>
                <div>
                    <button type="submit" class="btn btn-outline-danger">Aceptar</button>
                    <br>
                        {%if error%}
                        <div class="alert alert-warning" role="alert">
                            {{error}}
                        </div>
                        {%endif%}
                </div>
                <a href="{% url 'Landing:Landing'%}">Ir a Landing</a>
                <br>
                <a href="{% url 'Registro:Registro'%}">Registrarse</a>
            </div>
            </form>
        </div> 
    </div>
   
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

tarea/proyecto/tarea/templates/Login/registro-usuarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Como integrar Django y Bootstrap 4 </title>

    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %}
</head>
<body background="https://img.myloview.es/cuadros/patron-web-textura-para-fondo-de-pantalla-rellenos-fondo-de-la-pagina-web-400-119131393.jpg">
    <br>
    <div class="mx-auto" style="width: 200px;">
        <div class="container">
            <form action="" method="POST">
                <!-- init cifrado -->
                    {% csrf_token%}
                <!-- end cifrado -->
            <!-- init image -->
            <div class="form-group" style="text-align: center;"> 
                <br>
                <div style="text-align: center;">
                <img src="https://joesknowsfood.com/wp-content/uploads/2018/01/instagram-logo-vector-download-200x200.jpg" alt="..." class="rounded-circle" style="width: 100px;">
            </div>
            <!-- end image -->
            <br>
                <div class="form-group">
                    {% if form_get.username.value %}
                    {{ form_get.username }}
                    {% else %}
                    {{ form_get.username }}
                    {% endif %} 
                </div>
                <div class="form-group">
                    {% if form_get.first_name.value %}
                    {{ form_get.first_name }}
                    {% else %}
                    {{ form_get.first_name }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {% if form_get.last_name.value %}
                    {{ form_get.last_name }}
                    {% else %}
                    {{ form_get.last_name }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {% if form_get.password.value %}
                    {{ form_get.password }}
                    {% else %}
                    {{ form_get.password }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {% if form_get.email.value %}
                    {{ form_get.email }}
                    {% else %}
                    {{ form_get.email }}
                    {% endif %}
                </div>

                <button type="submit" class="btn btn-primary">Registrate
                </button>
            </div>
            </form>
        </div> 
    </div>
   
    {% bootstrap_javascript jquery='full' %}
</body>
</html>